name       : thunar-volman
version    : 4.18.0
release    : 1
source     :
    - https://archive.xfce.org/xfce/4.18/src/thunar-volman-4.18.0.tar.bz2 : 93b75c7ffbe246a21f4190295acc148e184be8df397e431b258d0d676e87fc65
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Automatic management of removable drives and media for Thunar.
description: |
    Automatic management of removable drives and media for Thunar.
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(thunarx-3)
setup      : |
    %configure --disable-debug
build      : |
    %make
install    : |
    %make_install
